#if !canImport(ObjectiveC)
import XCTest

extension PabloTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PabloTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PabloTests.__allTests__PabloTests),
    ]
}
#endif
